### ISSUE TITLE
Development mode does not work.

### ISSUE THREAD

**Issue by belfz** [kevguy/vue-hackernews-2.0-typescript#1]
Hello,

Running the application in development mode (via `npm run dev`) does not work. It fails with following error:

```
> vue-hackernews-2.0-typescript@1.0.0 dev /Users/marcin/projects/vue-hackernews-2.0-typescript
> node server

module.js:538
    throw err;
    ^

Error: Cannot find module './build/setup-dev-server'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/marcin/projects/vue-hackernews-2.0-typescript/server.js:53:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-hackernews-2.0-typescript@1.0.0 dev: `node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-hackernews-2.0-typescript@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Indeed, [a call to require in server.js:53](https://github.com/kevguy/vue-hackernews-2.0-typescript/blob/master/server.js#L53) is invalid - `./build/setup-dev-server` does not exist.

**Comment by kevguy** [comment]
Hi @belfz, thanks for the heads up, I actually forgot to commit `setup-dev-server.js` into the repo. It should be working fine now.
